##Datalab Semester 2

In [4]:
import sqlite3
import pandas as pd
import os

# Dit stukje code zorgt dat Python altijd in de map van het script zelf kijkt
current_path = os.getcwd()
db_path = os.path.join(current_path, 'database.sqlite')

# Check of het bestand wel echt bestaat voordat je verbindt
if os.path.exists(db_path):
    conn = sqlite3.connect(db_path)
    print("Verbinding geslaagd!")
else:
    print(f"Error: Kan database.sqlite niet vinden in {current_path}")

Verbinding geslaagd!

In [10]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
namen = [row[0] for row in cursor.fetchall()]
print(namen)

['sqlite_sequence', 'Player_Attributes', 'Player', 'Match', 'League', 'Country', 'Team', 'Team_Attributes']

In [6]:
query = "SELECT * FROM Team"

df_teams = pd.read_sql_query(query, conn)
df_teams.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [7]:
import pandas as pd
import sqlite3
import os

# Automatisch het juiste pad vinden, ongeacht waar je bent op je Mac
current_dir = os.path.dirname(os.path.abspath('__file__'))
db_path = os.path.join(current_dir, 'database.sqlite')

print(f"Ik zoek de database op: {db_path}")

conn = sqlite3.connect(db_path)
query = "SELECT * FROM Team WHERE team_long_name LIKE '%Barcelona%'"

df = pd.read_sql_query(query, conn)
df.head()

Ik zoek de database op: c:\Users\sasha\Documents\GitHub\Datalab_semester2_Groep1\notebook\database.sqlite

      id  team_api_id  team_fifa_api_id team_long_name team_short_name
0  43042         8634               241   FC Barcelona             BAR